# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b6f7007f9eca95d0670f17eb3fe5cd44cf1e5081c6b77c16900204dff0b9909fdaf616c81b9c6129fd552fc3c1585d4ebe9fc489df11c01867ec676f82d4267

test:
  secret_key_base: 4d008ea4e5acee772ba0ac3c397b7ba1317493ebdbddd9c2e7e89db69a6e9a1a52d6fce28176aeb9a1a35f6c45f8127d1f7dbd968d518646b97ed6b832acbfe3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
